apiVersion: v1
kind: Service
metadata:
  name: sample-app-h2-inmemory-db-service
spec:
  selector:
    app: sample-app-h2-inmemory-db
  ports:
    - protocol: TCP
      port: 9808
      targetPort: 30333
  type: NodePort
  